os:
  - linux
  # - osx
  # - windows
language: rust
rust:
  - stable
  # - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  # - cargo build --verbose
  # - cargo test --verbose
  - echo $AWS_ENDPOINT
  - echo $AWS_ACCESS_KEY_ID
  - echo $AWS_BUCKET
deploy:
  provider: s3
  endpoint: $AWS_ENDPOINT
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: ams
  on:
    all_branches: true
