os:
  - linux
  # - osx
  # - windows
language: rust
rust:
  - stable
  # - nightly
before_install:
  - sudo apt-get update
  - sudo apt-get install rclone
env:
  - RCLONE_CONFIG_RUSTCI_TYPE=swift RCLONE_CONFIG_RUSTCI_ENV_AUTH=true
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  # - cargo build --verbose
  # - cargo test --verbose
  - echo $OS_USERNAME
deploy:
  provider: script
  script: rclone sync /home/travis/build/thomas9911/openstack-client/target rustci:rustci
  on:
    all_branches: true
