os:
  - linux
  - osx
  - windows
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  # - cargo build --verbose
  # - cargo test --verbose
  - echo $AWS_ENDPOINT
  - echo $AWS_ACCESS_KEY
  - echo $AWS_BUCKET
deploy:
  provider: s3
  endpoint: $AWS_ENDPOINT
  skip_cleanup: true
  bucket: $AWS_BUCKET
  on:
    all_branches: true
