os:
  - linux
  # - osx
  # - windows
language: rust
rust:
  - stable
  # - nightly
# before_install:
#   - curl https://rclone.org/install.sh | sudo bash
# env:
#   - RCLONE_CONFIG_RUSTCI_TYPE=swift RCLONE_CONFIG_RUSTCI_ENV_AUTH=true
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --release --verbose
  - cargo test --release --verbose
  # - echo $OS_USERNAME
deploy:
  provider: script
  script: ls && pwd && ls /home/travis/build/thomas9911/openstack-client/target/release
  # script: /home/travis/build/thomas9911/openstack-client/target/release/openstack-client upload object --file /home/travis/build/thomas9911/openstack-client/target/release/openstack-client --name openstack-client --container rustci
  on:
    all_branches: true
