os:
  - linux
  - osx
  - windows
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
deploy:
  provider: s3
  endpoint: $AWS_ENDPOINT
  skip_cleanup: true
  bucket: $AWS_BUCKET