os:
  - linux
  # - osx
  # - windows
language: rust
rust:
  - stable
  # - nightly
before_install:
  - curl https://rclone.org/install.sh | sudo bash
env:
  - RCLONE_CONFIG_RUSTCI_TYPE=swift RCLONE_CONFIG_RUSTCI_ENV_AUTH=true
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --release --verbose
  - cargo test --release --verbose
  # - echo $OS_USERNAME
deploy:
  provider: script
  script: rclone sync --include openstack-client* /home/travis/build/thomas9911/openstack-client/target/release rustci:rustci
  on:
    all_branches: true
